//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Okazje.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Okazje.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;p style=&quot;text-align: center;&quot;&gt;
        ///  &lt;strong&gt;&lt;span style=&quot;color: #339966;&quot;&gt;$PRODUCT_NAME$&lt;/span&gt;&lt;/strong
        ///  &gt;&amp;nbsp;&lt;strong&gt;$PRODUCT_PRICE$&lt;/strong&gt;
        ///&lt;/p&gt;
        ///&lt;table style=&quot;margin-left: auto; margin-right: auto;&quot;&gt;
        ///  &lt;tbody&gt;
        ///    &lt;tr&gt;
        ///      &lt;td&gt;Id produktu :&lt;/td&gt;
        ///      &lt;td style=&quot;text-align: center;&quot;&gt;$product_id$&lt;/td&gt;
        ///    &lt;/tr&gt;
        ///    &lt;tr&gt;
        ///      &lt;td&gt;Poprzednia cena :&lt;/td&gt;
        ///      &lt;td style=&quot;text-align: center;&quot;&gt;$prev_price$&lt;/td&gt;
        ///    &lt;/tr&gt;
        ///    &lt;tr&gt;
        ///      &lt;td&gt;Przecena :&lt;/td&gt;
        ///      &lt;td style=&quot;text-align: center [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string MailBody {
            get {
                return ResourceManager.GetString("MailBody", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;p style=&quot;text-align: center;&quot;&gt;
        ///  &lt;strong&gt;&lt;span style=&quot;color: #ca0000;&quot;&gt;$ERROR_NAME$&lt;/span&gt;&lt;/strong
        ///  &gt;&amp;nbsp;&lt;strong&gt;$VARIABLES$&lt;/strong&gt;
        ///&lt;/p&gt;.
        /// </summary>
        internal static string MailErrorBody {
            get {
                return ResourceManager.GetString("MailErrorBody", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;p style=&quot;text-align: center;&quot;&gt;
        ///    &lt;strong&gt;&lt;span style=&quot;color: #339966;&quot;&gt;Problematyczne linki: &lt;/span&gt;&lt;/strong&gt;&amp;nbsp;&lt;strong&gt;$LINKS_COUNT$&lt;/strong&gt;
        ///&lt;/p&gt;
        ///&lt;table style=&quot;margin-left: auto; margin-right: auto;&quot;&gt;
        ///    &lt;tbody&gt;
        ///       $SINGLE_ITEM$
        ///    &lt;/tbody&gt;
        ///&lt;/table&gt;.
        /// </summary>
        internal static string MailLinksListBody {
            get {
                return ResourceManager.GetString("MailLinksListBody", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;tr&gt;
        ///            &lt;td&gt;Link:&lt;/td&gt;
        ///            &lt;td style=&quot;text-align: center;&quot;&gt;$PRODUCT_LINK$&lt;/td&gt;
        /// &lt;/tr&gt;.
        /// </summary>
        internal static string MailLinksListSingleItemBody {
            get {
                return ResourceManager.GetString("MailLinksListSingleItemBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap off {
            get {
                object obj = ResourceManager.GetObject("off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap on {
            get {
                object obj = ResourceManager.GetObject("on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
